#name: Scheduled Release
name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get current year, month and day
        run: |
          echo "BUILD_DATE_YEAR=$(date -u +'%Y')" >> $GITHUB_ENV
          echo "BUILD_DATE_MONTH=$(date -u +'%m')" >> $GITHUB_ENV
          echo "BUILD_DATE_DAY=$(date -u +'%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_NUMBER=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_DOT=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_HYPHEN=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Replace placeholders with current date
        run: |
          sed -i "s/version = \"dev\"/version = \"${{ env.BUILD_DATE_WITH_DOT }}\"/g" GuardMe.lua
          sed -i "s/## Version: dev/## Version: ${{ env.BUILD_DATE_WITH_DOT }}/g" GuardMe.txt
          sed -i "s/## AddOnVersion: 00000000/## AddOnVersion: ${{ env.BUILD_DATE_NUMBER }}/g" GuardMe.txt

      - name: Create ZIP archive
        run: |
          REPO_FOLDER=$(pwd)
          mkdir -p /tmp/GuardMe
          cp -r ./* /tmp/GuardMe
          rm -rf /tmp/GuardMe/{.git,.github,.gitignore}
          cd /tmp
          zip -r "$REPO_FOLDER/GuardMe-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip" ./GuardMe -x "*.git*" "*.github*" ".gitignore"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.BUILD_DATE_WITH_DOT }}"
          commit: ${{ github.ref }}
          tag: "${{ env.BUILD_DATE_WITH_DOT }}"
          artifacts: "GuardMe-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip"
          artifactContentType: application/zip
          bodyFile: CHANGELOG.md
          allowUpdates: true
          makeLatest: true

      - name: Send to ESOUI
        if: false
        env:
          ESOUI_API_KEY: ${{ secrets.ESOUI_API_KEY }}
          ADDON_ID: 0000
        run: |
          curl -X POST \
            -H "x-api-token: $ESOUI_API_KEY" \
            -F "id=${ADDON_ID}" \
            -F "version=${{ env.BUILD_DATE_WITH_DOT }}" \
            -F "updatefile=@GuardMe-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip" \
            -F "changelog=$(cat CHANGELOG.md)" \
            https://api.esoui.com/addons/update